### ISSUE TITLE
Session/Input and Crontab/CLI

### ISSUE THREAD

**Issue by matalina** [bcit-ci/CodeIgniter#1890]
I am running a serveral cronjobs on our intranet.  Before I upgraded to the current release of CI I was running error free.

Now I am getting:

```
<div>

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: REMOTE_ADDR</p>
<p>Filename: core/Input.php</p>
<p>Line Number: 351</p>

</div><div>

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /usr/local/www/webdev/corp_intranet/system/core/Exceptions.php:185)</p>
<p>Filename: libraries/Session.php</p>
<p>Line Number: 675</p>

</div> 
```

I know what the error means, and I can fix it myself, but I wanted to know if there is anyone else having this issue.  It only happens when I run on the cli/cronjobs regular pages run fine.

**Comment by KirksFletcher** [comment]
"Problem" seems to still exist in CI3 RC3, can we have someone fix this.

**Comment by kishor10d** [comment]
This is issue is resolved in current version of CodeIgniter-2.2.2
I am using this version for my project and confirmed after checking the code on line no. 351

**Comment by whyscream** [comment]
This issue still exists in CI 2.2.3, the error has moved to line 352. Looking at git history, I can't seem to find when the fix as described in https://github.com/bcit-ci/CodeIgniter/issues/1890#issuecomment-11178227 was ever committed.

Please re-open, the fix is trivial and known, so please apply it.

Output:
```
$ php index.php utils
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: REMOTE_ADDR</p>
<p>Filename: core/Input.php</p>
<p>Line Number: 352</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /var/www/domain.tld/backend-app/system/core/Exceptions.php:186)</p>
<p>Filename: libraries/Session.php</p>
<p>Line Number: 689</p>

</div>
```

**Comment by danilocolasso** [comment]
I'm using version 2.2.0 and this still happen.
- I modified ```/system/core/Input.php``` at the line 351 : That's ok.
- So, in my class  when i put ```parent::__construct();``` in my construct. this returns false

My class:

    <?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

    class Email extends CI_Controller {
    
        public function __construct() {
            parent::__construct();

            if (!$this->input->is_cli_request()) {
                show_error('Direct access is not allowed');
            }
        
            $this->load->model('email_model', 'model');
        }

        public function send() {
            ...
        }
    }
